services:
  frontend:
    build: ./frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${API_BASE_URL}
    ports:
      - 3000:3000
  api:
    build: ./backend
    restart: always
    ports:
      - 5000:5000
    environment:
      HOST: 0.0.0.0
      PORT: 5000
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
  db: 
    image: postgres
    restart: always
    volumes:
      - people-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
volumes:
  people-data:
 
