services:
  frontend:
    restart: always
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${API_BASE_URL}
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src
    command: npm run dev
  api:
    restart: always
    build: ./backend
    ports:
      - 5000:5000
    environment:
      HOST: 0.0.0.0
      PORT: 5000
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
  db: 
    restart: always
    image: postgres
    volumes:
      - people-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
volumes:
  people-data:
 
